### ISSUE TITLE
flutter_gallery_3d not scrolling when used inside a pageview

### ISSUE THREAD

**Issue by sahiram036** [lazyee/flutter_gallery_3d#2]
I am using your package inside a pageview and facing a issue is that flutter_gallery_3d view is not scrolling anymore
When I tried to scroll it, then main pageview is navigating but flutter_gallery_3d is not scrolling.

I just simply want that flutter_gallery_3d view should normally scroll as normal list and when I scroll outside then it must be navigate to next pageview screen.

**Comment by lazyee** [comment]
I fixed it,you can try flutter_gallery_3d: ^1.0.5

**Comment by sahiram036** [comment]
> I fixed it,you can try flutter_gallery_3d: ^1.0.5

Thank you, Its working perfectly!!!

**Comment by sahiram036** [comment]
Can you please look at this issue as well
[https://github.com/pharous-flutter/drawer_swip/issues/3]

**Comment by lazyee** [comment]
emmm,show me you code?

**Comment by sahiram036** [comment]
> emmm,show me you code?

Yes sure here it is..

``` Scaffold(
      extendBody: true,
      endDrawerEnableOpenDragGesture: false,
      key: _scaffoldKey, 
      body: LiquidPullToRefresh(
        key: _refreshIndicatorKey,
        color: AllColors.appColor,
        backgroundColor: Colors.white,
        onRefresh: _handleRefresh,
        showChildOpacityTransition: true,
        child: SwipeDrawer(
          radius: 20,
          key: drawerKey,
          hasClone: false,
          bodyBackgroundPeekSize: 30,
          backgroundColor: Colors.red, 
          drawer: buildDrawer(context),  // side drawer widget
        
          child:   buildBody() ,   // whole screen body
        ),
      ),
    );```
