### ISSUE TITLE
Transparent images

### ISSUE THREAD

**Issue by RobMrz** [lazyee/flutter_gallery_3d#6]
If I use transparent images. The background images automatically have a black opaque color applied to them. 
I don't see the application of color in the plugin source code and I'm not applying any in my own. Is Flutter or Dart applying this automatically? Would you know how to remove this color?

**Comment by lazyee** [comment]
Is isShowTransformMask an attribute you didn't set to false? It defaults to true

**Comment by RobMrz** [comment]
Oh I missed this, thank you
